### ISSUE TITLE
Unable to bucket by non-nested field with multiple Y-axis metrics

### ISSUE THREAD

**Issue by erkserkserks** [ppadovani/KibanaNestedSupportPlugin#68] opened 2018-05-09 19:02 UTC
**Plugin version**:
6.2.2-1.0.5 and 6.2.2-1.0.6

**Kibana version**:
6.2.2

**Plugins installed**:
KNQL only

**Description of the problem including expected versus actual behavior**:
When creating visualizations with multiple Y-axis metrics, it is not possible to bucket by a non-nested field.

This seems like a regression from plugin version 6.2.2-1.0.5 to 6.2.2-1.0.6.

The test data was generated using `scripts/nested-support/genData.py`
 
**Correct behavior (6.2.2-1.0.5) when bucketing by a non-nested field (both min and max metrics are visible):**
![correct](https://user-images.githubusercontent.com/2941377/39833271-98eccd78-5397-11e8-9a65-c57b018b13a5.png)

Elasticsearch request body:
```
{
  "size": 0,
  "_source": {
    "excludes": []
  },
  "aggs": {
    "3": {
      "terms": {
        "field": "cars_size",
        "size": 5,
        "order": {
          "1": "desc"
        }
      },
      "aggs": {
        "1": {
          "min": {
            "field": "family.age"
          }
        },
        "2": {
          "max": {
            "field": "family.age"
          }
        }
      }
    }
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [],
  "query": {
    "bool": {
      "must": [
        {
          "match_all": {}
        }
      ],
      "filter": [],
      "should": [],
      "must_not": []
    }
  }
}
```

**Incorrect behavior (6.2.2-1.0.6) when bucketing by a non-nested field (missing max metric):**
![incorrect](https://user-images.githubusercontent.com/2941377/39833287-a232b8fc-5397-11e8-8ada-afa7688ceb28.png)

Elasticsearch request body:
```
{
  "size": 0,
  "_source": {
    "excludes": []
  },
  "aggs": {
    "3": {
      "terms": {
        "field": "cars_size",
        "size": 5,
        "order": {
          "nested_1>1": "desc"
        }
      },
      "aggs": {
        "2": {
          "max": {
            "field": "family.age"
          }
        },
        "nested_1": {
          "nested": {
            "path": "family"
          },
          "aggs": {
            "1": {
              "min": {
                "field": "family.age"
              }
            }
          }
        }
      }
    }
  },
  "stored_fields": [
    "*"
  ],
  "script_fields": {},
  "docvalue_fields": [],
  "query": {
    "bool": {
      "must": [
        {
          "match_all": {}
        }
      ],
      "filter": [],
      "should": [],
      "must_not": []
    }
  }
}
```

**Errors in browser console (if relevant)**:
No errors in console

**Comment by ppadovani** [comment] 2018-05-10 13:52
Damn. I'll get it fixed pronto.

Sorry about that.

**Comment by ppadovani** [comment] 2018-05-10 14:20
This looks like a regression, but is in fact a different induction of this issue via an alternate order of operation. I'll get a fix in place.

**Comment by ppadovani** [comment] 2018-05-10 15:45
Fixed in 6.2.4-1.0.2 - Will start the back port in a few hours, shouldn't take long.

**Comment by erkserkserks** [comment] 2018-05-10 16:43
Awesome! Thanks once again :)

**Comment by ppadovani** [comment] 2018-05-10 19:59
Back ported for all 6.X releases.

**Closed** 2018-05-11 13:00 UTC
Labels: Fixed-Backporting
