### ISSUE TITLE
Only date fields showing in Discover with nested array of objects

### ISSUE THREAD

**Issue by Kazanz** [ppadovani/KibanaNestedSupportPlugin#53] opened 2018-03-23 01:40 UTC
First off.  Love your work.  This is a terrific plugin.

**Plugin version**:
6.2.2

**Kibana version**:
6.2.2

**Plugins installed**:
Just this one (besides defaults)

**Description of the problem including expected versus actual behavior**:
There is an array of objects under a field called `services`. These objects have a variety of fields `date`, `number`, and `text`.  In the discover section, only the `date` fields appear.  In the visualization section, all fields are available.  See images

<img width="221" alt="screen shot 2018-03-22 at 9 32 08 pm" src="https://user-images.githubusercontent.com/7441147/37806951-37c7baec-2e19-11e8-8f8a-f70d41acadf7.png">
<img width="221" alt="screen shot 2018-03-22 at 9 32 08 pm" src="https://user-images.githubusercontent.com/7441147/37807014-7e4e2ece-2e19-11e8-893e-0aa58f1f31eb.jpg">

**Steps to reproduce**:
 1.  Add a field to a document who's value is an array of objects with `date` and `text` values for its fields.
 2. Create your Index patterns and check your nested fields settings
 3. Go to discover section and look in left bar.

**Errors in browser console (if relevant)**:

**Provide logs and/or server output (if relevant)**:

**Comment by ppadovani** [comment] 2018-03-23 11:55
Thanks for the feedback. If I understand you right, you are talking about the left hand pane that allows one to add a field as a column to the output display? Sort of like this?
<img width="1084" alt="screen shot 2018-03-23 at 6 48 51 am" src="https://user-images.githubusercontent.com/11234684/37827631-433615d4-2e66-11e8-9ab2-eea131063f24.png">

If this is the case, I purposely did not add the ability to add a nested field as a column on the discover page. If you look in the screenshot above you can see that the structure viewer shows you the nested fields nicely, and has filter controls for each, but the ability to add a nested field as a column is not available. My reasoning for not adding this, was that I didn't quite know how to display a list of ALL of the values in the record for the specified field in the column in a way that would make sense. Do I show a common delimited list? A JSON array? An HTML list with a scroll bar? None of these seemed to make sense. I am open to suggestions on what to do here.

If this is not the case, then please clarify this issue a bit more, as I seem to be either a bit dense or need more coffee... likely the latter. :-)

(BTW: In the scripts directory of this GitHub repo there are the scripts I use to create the test data I use to test and validate my plugin. If I'm missing an edge case in my dataset please let me know. You can also use them to generate a bogus set of data to illustrate a problem you are seeing without having to expose your own internal datasets.)

**Comment by ppadovani** [comment] 2018-03-23 13:58
Ok... I've had my coffee... I think this is what you are referring to:
![screen shot 2018-03-23 at 8 54 52 am](https://user-images.githubusercontent.com/11234684/37832854-d9bf4140-2e77-11e8-9545-e7822e52bb14.png)

The ability to select an additive or subtractive filter from the field... This is supported through the 'Structure' view of the document, but you are correct the fields are not showing up in the list and allowing one to filter from there. I will look at what needs to be done to add this functionality. Here is what I propose to do:

- Nested fields will not be allowed to be added as a column, per my current functionality. I just don't see a usable way yet to display this.
- Nested fields will have a twistie on each top level object that can be expanded. Within the sublist inside the twistie the same functionality that exists in Kibana now will exist where you can add an additive or subtractive filter. I'll work on this during the upcoming weekend.

Thoughts?

**Comment by ppadovani** [comment] 2018-03-24 20:39
I have a fix released in 6.2.2-1.0.1, please download and test. If this fix works, please update this issue. 

Please do not close this issue, as I'll close it after I have ported the fix to all of the main releases.

**Closed** 2018-03-30 14:24 UTC

**Comment by ppadovani** [comment] 2018-04-03 00:03
I found a regression #57 due to this fix. I have a new release out that I believe fixes this issue. It also **replaces** the 'Table' doc viewer with the 'Structure' viewer to create a more seamless experience. Can you please grab the latest release and make sure that I have not regressed this particular issue? My testing seems to indicate that all is good.

Thanks!
